language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - 'gem update --system'
  - 'gem install compass'
  - 'npm install -g grunt-cli'
before_script:
  - 'npm install -g bower'
  - 'bower install'